print("Day 2")
print()
print("Getting to know you!")
print()
YourName = input("What's your name?: ")
Hungry = input ("What's your favorite food?: ")
Music = input("What's your favorite music? ")
WhereAreYou = input("Where do you live?: ")
print() 
print("You are")
print(YourName)
print("You're probably hungry for")
print(Hungry)
print("and you're definitely getting your groove on to")
print (Music)
print ("living in the amazing")
print (WhereAreYou)
print()
print("#replit100DaysOfCode")
